### ISSUE TITLE
Fail to parse yaml file

### ISSUE THREAD

**Issue by fyeeme** [intlify/bundle-tools#127]
### Reporting a bug?

file to parse yaml messages that values contains space.
<img width="604" alt="image" src="https://user-images.githubusercontent.com/6078758/173290675-11673de6-345e-43ad-9a80-8b10f1098580.png">
<img width="386" alt="image" src="https://user-images.githubusercontent.com/6078758/173290706-74b5783d-636a-4a1d-9cf6-1ac3d039b265.png">

<img width="1511" alt="image" src="https://user-images.githubusercontent.com/6078758/173290928-04583fe2-71ca-42d0-b0f4-dbd618fdd8d3.png">

### Expected behavior

yaml format should be correct parse that values has space:

```yaml
  desc: Opinionated Vite Starter Template
```

### Reproduction
[demo](https://github.com/conferer/vue-workspace/tree/main/packages/web-client)
create a i18n message yaml format. then add following content:

```yaml
button:
  about: About
  back: Back
  go: GO
  home: Home
  toggle_dark: Toggle dark mode
  toggle_langs: Change languages
intro:
  desc: Opinionated Vite Starter Template
  dynamic-route: Demo of dynamic route
  hi: Hi, {name}!
  aka: Also known as
  whats-your-name: What's your name?
not-found: Not found
```

npm run dev to start vite project, and error will occured.

![Uploading image.png…]()

### Issue Package

vite-plugin-vue-i18n

### System Info

```shell
system: macos 12.1
node: v16.15.1
pnpm: 7.1.6
chrome: Version 102.0.5005.115 (Official Build) (arm64)
package.json:

{
  "name": "web-client",
  "private": true,
  "version": "0.0.0",
  "scripts": {
    "dev": "vite",
    "build": "vue-tsc --noEmit && vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "@shimi-edu/api": "workspace:*",
    "pinia": "^2.0.14",
    "vue": "^3.2.37",
    "vue-i18n": "9",
    "vue-router": "^4.0.16"
  },
  "devDependencies": {
    "@intlify/vite-plugin-vue-i18n": "^3.4.0",
    "@vitejs/plugin-vue": "^2.3.3",
    "prettier": "^2.6.2",
    "typescript": "^4.7.3",
    "vite": "^2.9.12",
    "vue-tsc": "^0.34.17"
  }
}
```

### Screenshot

<img width="1511" alt="image" src="https://user-images.githubusercontent.com/6078758/173290940-a2e5914f-cb7f-4812-8901-9802021a36be.png">

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/intlify/bundle-tools/blob/main/.github/contributing.md).
- [X] Read the README
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/intlify/bundle-tools/discussions).
